<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Migrations\20211222115010_Initial_SQL_Data.sql" />
    <None Remove="Migrations\20241009055525_Version_V31_Data.sql" />
    <None Remove="Migrations\20241022085703_Version_V4_Data.sql" />
    <None Remove="Migrations\20250214054551_Version_V5_Data.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\20211222115010_Initial_SQL_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20241009055525_Version_V31_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20241022085703_Version_V4_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20250214054551_Version_V5_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20250623073035_Version_V8_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20250505093213_Version_V7_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Migrations\20250402120541_Version_V6_Data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentManagement.Data\DocumentManagement.Data.csproj" />
  </ItemGroup>

</Project>
